#! /bin/sh

bspc config border_width         2
bspc config window_gap           6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding          18

bspc config normal_border_color  "#777a7f"
bspc config active_border_color  "#ef476f"
bspc config focused_border_color "#5599ff"
